[[plugins]]
repo = 'arcticicestudio/nord-vim'
hook_add = '''
  colorscheme nord
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/denite.vim
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = "airblade/vim-gitgutter"

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    source ~/.config/nvim/plugins/lightline.vim
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = "neoclide/coc.nvim"
merge = 0
rev = "release"
build = './install.sh nightly'
hook_add = '''
    source ~/.config/nvim/plugins/coc.vim
'''

[[plugins]]
repo = 'fatih/vim-go'
hook_add = '''
    source ~/.config/nvim/plugins/vim-go.vim
'''

[[plugins]]
repo = 'leafgarland/typescript-vim'
hook_add = '''
    source ~/.config/nvim/plugins/typescript-vim.vim
'''

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
hook_add = '''
    hi link tsxTagName htmlTag
    hi link tsxTag htmlTag
    hi link tsxCloseTag htmlEndTag
    hi link tsxCloseString htmlEndTag
'''

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']

[[plugins]]
repo = 'ekalinin/Dockerfile.vim'

[[plugins]]
repo = 'hashivim/vim-terraform'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'ngmy/vim-rubocop'

[[plugins]]
repo = 'slim-template/vim-slim'

[[plugins]]
repo = 'chr4/nginx.vim'

